import type { VariantCharacter } from './variantTypes';

/**
 * ── The Pantheon roster ───────────────────────────────────────────────────────
 * The Pantheon skin (Millennial only) is "many themes in one": choosing a patron
 * — a Greek god, hero or monster, or a figure of Norse myth — re-skins the whole
 * app in their palette. Like the Avengers roster, each figure is data: design-
 * token overrides applied to :root as inline custom properties. Tones are refined
 * and classical to suit the calm Millennial mode. "Mood" figures also override
 * the structural tokens to commit to a temple/underworld/night backdrop.
 *
 * `signature` maps to an ambient effect in pantheon/PantheonEffects.tsx; `voice`
 * rewrites key copy in the figure's own register. Groups: god · hero · monster ·
 * norse.
 */

export const GREEK_CHARACTERS: VariantCharacter[] = [
  // ── Olympians ─────────────────────────────────────────────────────────────────
  {
    id: 'zeus',
    name: 'Zeus',
    alias: 'King of the Gods',
    group: 'god',
    quote: 'The sky itself answers to me.',
    signature: 'thunder',
    voice: {
      greeting: 'The heavens attend you.',
      capture: 'Decree it from Olympus…',
      logButton: 'Decree',
      empty: 'Even Olympus began with a single throne. Take yours.',
    },
    vars: {
      '--primary': '222 60% 42%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '43 74% 52%',
      '--accent-foreground': '30 60% 12%',
      '--ring': '222 70% 55%',
      '--av-energy': '48 95% 65%',
    },
  },
  {
    id: 'poseidon',
    name: 'Poseidon',
    alias: 'Lord of the Sea',
    group: 'god',
    quote: 'The tides rise at my word.',
    signature: 'tide',
    voice: {
      greeting: 'The tides are yours to command.',
      capture: 'Speak to the deep…',
      logButton: 'Summon',
      empty: 'Still waters. Cast your first thought.',
    },
    vars: {
      '--background': '205 55% 10%',
      '--surface': '205 45% 14%',
      '--surface-hover': '205 40% 19%',
      '--elevated': '205 45% 16%',
      '--overlay': '205 60% 3%',
      '--foreground': '190 25% 92%',
      '--muted': '205 35% 18%',
      '--muted-foreground': '195 18% 70%',
      '--subtle': '200 15% 55%',
      '--border': '205 30% 24%',
      '--border-strong': '205 32% 34%',
      '--primary': '185 62% 44%',
      '--primary-foreground': '205 55% 8%',
      '--accent': '28 70% 55%',
      '--accent-foreground': '205 40% 10%',
      '--ring': '185 70% 50%',
      '--av-energy': '185 80% 55%',
    },
  },
  {
    id: 'hades',
    name: 'Hades',
    alias: 'Lord of the Underworld',
    group: 'god',
    quote: 'All roads lead, at last, to me.',
    signature: 'embers',
    voice: {
      greeting: 'The unseen world welcomes you.',
      capture: 'Record among the shades…',
      logButton: 'Inter',
      empty: 'The realm below is quiet. Give it something to keep.',
    },
    vars: {
      '--background': '270 18% 8%',
      '--surface': '270 16% 11%',
      '--surface-hover': '272 16% 16%',
      '--elevated': '270 16% 13%',
      '--overlay': '270 30% 2%',
      '--foreground': '270 10% 90%',
      '--muted': '270 14% 16%',
      '--muted-foreground': '270 8% 62%',
      '--subtle': '270 8% 48%',
      '--border': '270 14% 22%',
      '--border-strong': '272 16% 32%',
      '--primary': '18 78% 52%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '265 55% 60%',
      '--accent-foreground': '0 0% 100%',
      '--ring': '18 80% 55%',
      '--av-energy': '20 90% 55%',
    },
  },
  {
    id: 'athena',
    name: 'Athena',
    alias: 'Goddess of Wisdom',
    group: 'god',
    quote: 'Wisdom is the truest armour.',
    signature: 'wings',
    voice: {
      greeting: 'Wisdom favours the prepared.',
      capture: 'Set down your strategy…',
      logButton: 'Reason',
      empty: 'A blank tablet — the beginning of wisdom.',
    },
    vars: {
      '--primary': '40 44% 44%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '210 30% 48%',
      '--accent-foreground': '0 0% 100%',
      '--ring': '44 55% 50%',
      '--av-energy': '48 55% 62%',
    },
  },
  {
    id: 'apollo',
    name: 'Apollo',
    alias: 'God of the Sun',
    group: 'god',
    quote: 'Let there be light, and music.',
    signature: 'radiance',
    voice: {
      greeting: 'Let there be light.',
      capture: 'Compose your verse…',
      logButton: 'Illuminate',
      empty: 'The sun rises on an empty day. Begin.',
    },
    vars: {
      '--primary': '38 88% 52%',
      '--primary-foreground': '30 60% 12%',
      '--accent': '20 80% 55%',
      '--accent-foreground': '0 0% 100%',
      '--ring': '42 90% 58%',
      '--av-energy': '45 100% 68%',
    },
  },
  {
    id: 'artemis',
    name: 'Artemis',
    alias: 'Goddess of the Hunt',
    group: 'god',
    quote: 'The moon lights my aim.',
    signature: 'moonlight',
    voice: {
      greeting: 'The hunt begins.',
      capture: 'Mark your quarry…',
      logButton: 'Loose',
      empty: 'The moon is high and the forest still. Track your first.',
    },
    vars: {
      '--background': '222 24% 11%',
      '--surface': '222 20% 14%',
      '--surface-hover': '222 18% 19%',
      '--elevated': '222 20% 16%',
      '--overlay': '222 40% 3%',
      '--foreground': '210 20% 92%',
      '--muted': '222 18% 18%',
      '--muted-foreground': '215 14% 70%',
      '--subtle': '215 12% 55%',
      '--border': '222 18% 24%',
      '--border-strong': '222 20% 34%',
      '--primary': '205 45% 60%',
      '--primary-foreground': '222 30% 10%',
      '--accent': '45 45% 68%',
      '--accent-foreground': '222 30% 12%',
      '--ring': '205 55% 64%',
      '--av-energy': '205 70% 78%',
    },
  },
  {
    id: 'aphrodite',
    name: 'Aphrodite',
    alias: 'Goddess of Love',
    group: 'god',
    quote: 'Beauty is its own power.',
    signature: 'petals',
    voice: {
      greeting: 'Beauty attends you.',
      capture: 'Whisper your heart…',
      logButton: 'Adore',
      empty: 'Nothing yet — so create something beautiful.',
    },
    vars: {
      '--primary': '342 55% 58%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '38 55% 70%',
      '--accent-foreground': '30 50% 14%',
      '--ring': '342 60% 62%',
      '--av-energy': '340 70% 72%',
    },
  },
  // ── Heroes & Champions ────────────────────────────────────────────────────────
  {
    id: 'heracles',
    name: 'Heracles',
    alias: 'The Twelve Labours',
    group: 'hero',
    quote: 'No labour is beyond me.',
    signature: 'quake',
    voice: {
      greeting: 'Strength honours you.',
      capture: 'Name your next labour…',
      logButton: 'Labour',
      empty: 'Twelve labours began with one. Start yours.',
    },
    vars: {
      '--primary': '28 55% 42%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '42 70% 52%',
      '--accent-foreground': '30 60% 12%',
      '--ring': '28 60% 48%',
      '--av-energy': '30 80% 55%',
    },
  },
  {
    id: 'perseus',
    name: 'Perseus',
    alias: 'Slayer of Medusa',
    group: 'hero',
    quote: 'Face the monster in the mirror.',
    signature: 'wings',
    voice: {
      greeting: 'Face it without fear.',
      capture: 'Record the deed…',
      logButton: 'Strike',
      empty: 'No monsters yet. Ready your shield.',
    },
    vars: {
      '--primary': '35 45% 46%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '200 15% 70%',
      '--accent-foreground': '210 30% 14%',
      '--ring': '35 55% 50%',
      '--av-energy': '195 40% 72%',
    },
  },
  {
    id: 'atalanta',
    name: 'Atalanta',
    alias: 'The Swift Huntress',
    group: 'hero',
    quote: 'Outrun me — if you can.',
    signature: 'moonlight',
    voice: {
      greeting: 'Swift and sure.',
      capture: 'Loose a thought…',
      logButton: 'Sprint',
      empty: 'The race is unrun. Take your mark.',
    },
    vars: {
      '--primary': '150 40% 38%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '42 70% 52%',
      '--accent-foreground': '30 60% 12%',
      '--ring': '150 48% 44%',
      '--av-energy': '140 60% 55%',
    },
  },
  {
    id: 'nike',
    name: 'Nike',
    alias: 'Winged Victory',
    group: 'hero',
    quote: 'Victory follows those who dare.',
    signature: 'radiance',
    voice: {
      greeting: 'Victory is near.',
      capture: 'Claim your triumph…',
      logButton: 'Triumph',
      empty: 'No victories yet. Earn your first.',
    },
    vars: {
      '--primary': '44 72% 52%',
      '--primary-foreground': '30 60% 12%',
      '--accent': '35 60% 66%',
      '--accent-foreground': '30 50% 14%',
      '--ring': '44 80% 58%',
      '--av-energy': '48 95% 70%',
    },
  },
  // ── Monsters & Titans ─────────────────────────────────────────────────────────
  {
    id: 'medusa',
    name: 'Medusa',
    alias: 'The Gorgon',
    group: 'monster',
    quote: 'Meet my gaze, if you dare.',
    signature: 'serpents',
    voice: {
      greeting: 'Meet my gaze — if you dare.',
      capture: 'Etch it in stone…',
      logButton: 'Petrify',
      empty: 'Nothing turned to stone yet. Begin.',
    },
    vars: {
      '--background': '150 18% 10%',
      '--surface': '150 16% 13%',
      '--surface-hover': '150 15% 18%',
      '--elevated': '150 16% 15%',
      '--overlay': '150 30% 2%',
      '--foreground': '120 12% 88%',
      '--muted': '150 14% 18%',
      '--muted-foreground': '140 10% 62%',
      '--subtle': '140 10% 48%',
      '--border': '150 14% 24%',
      '--border-strong': '150 16% 33%',
      '--primary': '130 50% 42%',
      '--primary-foreground': '150 40% 8%',
      '--accent': '150 8% 60%',
      '--accent-foreground': '150 30% 12%',
      '--ring': '130 60% 46%',
      '--av-energy': '125 75% 48%',
    },
  },
  {
    id: 'minotaur',
    name: 'Minotaur',
    alias: 'Beast of the Labyrinth',
    group: 'monster',
    quote: 'Every path leads back to me.',
    signature: 'quake',
    voice: {
      greeting: 'The labyrinth remembers.',
      capture: 'Thread the maze…',
      logButton: 'Charge',
      empty: 'Empty halls. Lay the first passage.',
    },
    vars: {
      '--background': '12 25% 10%',
      '--surface': '12 22% 13%',
      '--surface-hover': '12 20% 18%',
      '--elevated': '12 22% 15%',
      '--overlay': '12 40% 2%',
      '--foreground': '20 15% 90%',
      '--muted': '12 18% 18%',
      '--muted-foreground': '16 12% 62%',
      '--subtle': '14 12% 48%',
      '--border': '12 18% 24%',
      '--border-strong': '12 20% 33%',
      '--primary': '14 62% 48%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '35 55% 52%',
      '--accent-foreground': '12 40% 10%',
      '--ring': '14 68% 52%',
      '--av-energy': '16 80% 52%',
    },
  },
  {
    id: 'kronos',
    name: 'Kronos',
    alias: 'Titan of Time',
    group: 'monster',
    quote: 'I devour all things, in the end.',
    signature: 'quake',
    voice: {
      greeting: 'Time bends to the patient.',
      capture: 'Set it against the ages…',
      logButton: 'Devour',
      empty: 'Time stretches empty. Give it something to consume.',
    },
    vars: {
      '--background': '40 12% 9%',
      '--surface': '40 10% 12%',
      '--surface-hover': '40 9% 17%',
      '--elevated': '40 10% 14%',
      '--overlay': '40 20% 2%',
      '--foreground': '42 14% 88%',
      '--muted': '40 10% 17%',
      '--muted-foreground': '40 8% 60%',
      '--subtle': '40 8% 46%',
      '--border': '40 10% 23%',
      '--border-strong': '42 12% 32%',
      '--primary': '42 45% 50%',
      '--primary-foreground': '40 30% 8%',
      '--accent': '265 30% 55%',
      '--accent-foreground': '0 0% 100%',
      '--ring': '42 55% 54%',
      '--av-energy': '45 60% 58%',
    },
  },
  // ── The Norse ─────────────────────────────────────────────────────────────────
  {
    id: 'odin',
    name: 'Odin',
    alias: 'The Allfather',
    group: 'norse',
    quote: 'I gave an eye for wisdom.',
    signature: 'wings',
    voice: {
      greeting: 'The Allfather sees all.',
      capture: 'Carve the runes…',
      logButton: 'Inscribe',
      empty: 'The nine realms are quiet. Speak the first rune.',
    },
    vars: {
      '--background': '220 20% 10%',
      '--surface': '220 18% 13%',
      '--surface-hover': '220 16% 18%',
      '--elevated': '220 18% 15%',
      '--overlay': '220 35% 2%',
      '--foreground': '210 15% 90%',
      '--muted': '220 16% 18%',
      '--muted-foreground': '212 12% 64%',
      '--subtle': '212 10% 50%',
      '--border': '220 16% 24%',
      '--border-strong': '220 18% 33%',
      '--primary': '212 40% 52%',
      '--primary-foreground': '220 30% 8%',
      '--accent': '42 62% 55%',
      '--accent-foreground': '220 30% 10%',
      '--ring': '212 50% 56%',
      '--av-energy': '212 65% 66%',
    },
  },
  {
    id: 'thor',
    name: 'Thor',
    alias: 'God of Thunder',
    group: 'norse',
    quote: 'The storm answers to Mjölnir.',
    signature: 'thunder',
    voice: {
      greeting: 'Raise your hammer.',
      capture: 'Strike a thought…',
      logButton: 'Strike',
      empty: 'The storm waits. Call the first bolt.',
    },
    vars: {
      '--primary': '210 40% 46%',
      '--primary-foreground': '0 0% 100%',
      '--accent': '32 55% 52%',
      '--accent-foreground': '30 60% 12%',
      '--ring': '210 50% 52%',
      '--av-energy': '205 80% 65%',
    },
  },
  {
    id: 'freya',
    name: 'Freya',
    alias: 'Goddess of Love & War',
    group: 'norse',
    quote: 'Half the slain are mine.',
    signature: 'moonlight',
    voice: {
      greeting: 'The falcon takes flight.',
      capture: 'Speak, and be adored…',
      logButton: 'Bestow',
      empty: 'Fólkvangr is empty. Fill its halls.',
    },
    vars: {
      '--primary': '35 60% 52%',
      '--primary-foreground': '30 60% 12%',
      '--accent': '342 45% 60%',
      '--accent-foreground': '0 0% 100%',
      '--ring': '35 68% 56%',
      '--av-energy': '38 80% 65%',
    },
  },
  {
    id: 'brynhildr',
    name: 'Brynhildr',
    alias: 'The Valkyrie',
    group: 'norse',
    quote: 'I choose who joins the honoured dead.',
    signature: 'wings',
    voice: {
      greeting: 'Chosen of the slain.',
      capture: 'Record the fallen…',
      logButton: 'Choose',
      empty: 'The hall awaits its heroes. Name the first.',
    },
    vars: {
      '--background': '215 25% 11%',
      '--surface': '215 22% 14%',
      '--surface-hover': '215 20% 19%',
      '--elevated': '215 22% 16%',
      '--overlay': '215 40% 3%',
      '--foreground': '205 18% 92%',
      '--muted': '215 20% 18%',
      '--muted-foreground': '208 14% 68%',
      '--subtle': '208 12% 54%',
      '--border': '215 20% 24%',
      '--border-strong': '215 22% 34%',
      '--primary': '210 30% 60%',
      '--primary-foreground': '215 30% 10%',
      '--accent': '44 65% 58%',
      '--accent-foreground': '215 30% 12%',
      '--ring': '210 40% 64%',
      '--av-energy': '150 55% 60%',
    },
  },
];

/** The figure shown if the Pantheon skin is active but none is chosen yet. */
export const DEFAULT_GREEK_ID = 'zeus';
export const GREEK_CHARACTER_IDS: string[] = GREEK_CHARACTERS.map((c) => c.id);
